title: Qian Dai's Homepage
page-top-title: Qian Dai
top-section-bg-text: Software Engineering, School of Computer Science, Fudan University.
home-subtitle: Qian Dai&ensp;|&ensp;代乾
copyright-text: '&copy; Qian Dai 2023-2024. All Rights Reserved.'
